#!/usr/bin/env sh

echo "Build script need to be updated. In the mean time, use the Docker files:"

echo "docker build -t yaml2json --file Dockerfile-yaml2json ."
echo "docker build -t json2yaml --file Dockerfile-json2yaml ."

echo "usage:"
echo "cat examples/example.yaml| docker run -i --rm yaml2json"
echo "cat examples/example.json| docker run -i --rm json2yaml"

exit 1

set -e

rm -rf bin

export GOPATH=$(pwd)/vendor

mkdir -p $GOPATH

echo "Download Dependency"
go get github.com/ghodss/yaml

for arch in amd64; do
    for OS in darwin linux; do
        for app in json2yaml yaml2json; do
            output="bin/$app-$OS-$arch"

            echo "Compiling $app for $OS"
            GOOS="$OS" GOARCH="$arch" go build -o "$output" "$app.go"
            echo "Created $output"
            echo ""
        done
    done
done

echo "Done"
